defaultPlacement: end
enableVersioning: true
handle: answers
name: answers
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5b8a19e1-3b40-499b-ba87-f5d0b0d07c9b: # reclaim-your-city
    enabledByDefault: true
    hasUrls: true
    template: answers/_entry
    uriFormat: 'answers/{slug}'
type: channel
